name = "aiau-site"
main = "src/worker.ts"
compatibility_date = "2025-09-24"

# Serve static assets produced by Vite from the dist directory
assets = { directory = "./dist" }

# Add routes/custom domain later via Cloudflare dashboard:
# - DNS: aiau.group -> Cloudflare
# - Workers Routes: aiau.group/* -> this worker


