name = "aiau"
main = "src/worker.ts"
compatibility_date = "2025-09-24"

[build]
command = "npm run build"

# Serve static assets produced by Vite from the dist directory
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

# Optional: set routes when binding a custom domain in code
# routes = [
#   { pattern = "aiau.group/*", zone_name = "aiau.group" }
# ]

# Add routes/custom domain later via Cloudflare dashboard:
# - DNS: aiau.group -> Cloudflare
# - Workers Routes: aiau.group/* -> this worker


